services:
  remote-control:
    build:
      context: ./remote-control
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - remote-control/.env

  redis:
    image: redis:7.4
    container_name: discord-iptv-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  newrelic-infra:
    container_name: newrelic-infra
    build:
      context: ./new-relic-infra
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

volumes:
  redis-data:
